pipeline:

  python-3.6.4-common.Dockerfile:
    image: plugins/docker
    registry: docker.force.fm
    repo: docker.force.fm/msa/python-common
    dockerfile: python-3.6.4-common.Dockerfile
    tags: [ 3.6.4 ]
    secrets: [ docker_username, docker_password ]

  python-3.6.4-test.Dockerfile:
    image: plugins/docker
    registry: docker.force.fm
    repo: docker.force.fm/msa/python-test
    dockerfile: ppython-3.6.4-test.Dockerfile
    tags: [ 3.6.4 ]
    secrets: [ docker_username, docker_password ]

  notify-users-with-telegram:
    image: appleboy/drone-telegram
    when:
      status: [ success, failure ]
      event: [ push, tag, deployment, pull_request ]

    secrets:
      - source: telegram_api_token
        target: telegram_token
      - source: telegram_receivers
        target: telegram_to
